name: Cypress Tests

on:
  pull_request:
    branches:
      - main
      - '**'   # Optional: run on every pushed branch
  push:
    branches:
      - main
      - '**'   # Optional: run on every pushed branch

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install    

      - name: Run Cypress tests
        run: npm run cypress:run